"""
Human-readable metadata about each check, used when building the
long-format issues table: what to call it, and which raw column(s)
it's actually about.
"""

from .checks import MAZE_COLS, MAZE_TIMEOUT_MS, SOA_TIMEOUT_MS, STROOP_TIMEOUT_MS

CHECK_DESCRIPTIONS = {
    "maze_errk_not_gt_overk": "Total errors should always be higher than overrun errors, since overruns are just one type of error -- but here total errors is equal to or lower than overruns.",
    "maze_trlsk_below_floor": "Fewer than 2 trials were recorded, but completing the maze twice in a row always takes at least 2 trials, so this can't be right.",
    "maze_trlsk_implausibly_high": "More than 50 trials were needed to finish the maze, which is unusually high.",
    "maze_compk_not_gt_initk": "Total completion time should always be longer than path-learning time (since completion time includes path-learning plus the two final clean trials), but here it's equal to or shorter.",
    "maze_compk_eq_0": "Completion time is zero or negative, which isn't possible for a real attempt at the maze.",
    "maze_compk_over_timeout": f"Completion time exceeds the task's own {MAZE_TIMEOUT_MS // 60_000} minute timeout limit.",
    "maze_initk_over_timeout": f"Path-learning time exceeds the task's own {MAZE_TIMEOUT_MS // 60_000} minute timeout limit.",
    "maze_partial_missing": "Some Maze variables are missing while others are present, even though a timeout should make all of them missing together.",
    "maze_errk_zero_impossible": "Zero total errors were recorded, which isn't possible -- the maze path is hidden, so the very first trial is guaranteed to include at least one wrong turn.",
    "maze_overk_zero_review": "Zero overrun errors were recorded -- unusual, but not impossible, since the guaranteed error doesn't have to be an overrun specifically. Worth a manual check.",
    "maze_initk_zero_impossible": "Path-learning time is zero, which isn't possible -- the guaranteed erroneous trial must have taken some real amount of time.",
    "maze_trlsk_eq_2_impossible": "Exactly 2 trials were recorded, which isn't possible -- the first trial can never be error-free, so completing the maze always takes at least 3 trials in practice.",
    "maze_negative_value": "One or more Maze variables has a negative value, which shouldn't happen for any of them.",
    "maze_non_integer_value": "Errors, overruns, or trial count has a fractional value (like 3.5), but these should always be whole numbers.",
    "gng_fpk_out_of_range": "g2fpk > 42",
    "gng_fnk_out_of_range": "g2fnk > 126",
    "gng_errk_out_of_range": "g2errk > 168",
    "gng_errk_consistency": "g2errk != g2fnk + g2fpk",
    "gng_avrtk_impossible": "g2avrtk present while g2fnk == 126 (no correct trials possible)",
    "gng_never_pressed_bug": "g2fnk==126 & g2fpk==0 -> should be fully missing, not literal 126/0",
    "stroop_vcrtne_out_of_range": f"vcrtne > {STROOP_TIMEOUT_MS}ms (corrected timeout threshold)",
    "stroop_vcrtne2_out_of_range": f"vcrtne2 > {STROOP_TIMEOUT_MS}ms (corrected timeout threshold)",
    "stroop_rt1_present_score1_zero": "vcrtne present while vi_sco1 == 0 (contradiction)",
    "stroop_rt2_present_score2_zero": "vcrtne2 present while vi_sco2 == 0 (contradiction)",
    "stroop_sco1_should_be_missing_bug": "vcrtne missing & vi_sco1==0 -> known bug, vi_sco1 should be relabeled missing",
    "stroop_sco2_should_be_missing_bug": "vcrtne2 missing & vi_sco2==0 -> known bug, vi_sco2 should be relabeled missing",
    "ds_invalid_value_1_or_2": "digitsp in {1,2} -- invalid per dictionary (valid: {0,3..9})",
    "ds_missing_mismatch": "digitot/digitsp missing status doesn't match (should be missing together)",
    "ds_zero_logic_contradiction": "digitsp==0 with digitot>0, or vice versa",
    "SoA_dur2_over_timeout": f"Completion time (esoadur2) exceeds the task's documented {SOA_TIMEOUT_MS // 1000}-second timeout limit.",
    "SoA_dur2_eq_0": "Completion time (esoadur2) is zero or negative, which isn't possible for a real attempt.",
    "SoA_dur2_below_5000": "Completion time (esoadur2) is 5,000ms or less, which is unusually fast.",
    "SoA_err2_gt_25": "Error count (esoaerr2) exceeds the documented cap of 25.",
    "SoA_err2_negative": "Error count (esoaerr2) is negative, which isn't possible.",
    "SoA_err2_non_integer": "Error count (esoaerr2) has a fractional value (like 3.5), but it should always be a whole number.",
    "SoA_conn2_eq_0": "Average connection time (scavr0t2) is zero or negative, which isn't possible for a real attempt.",
    "SoA_dur2_err2_zero_timeout_bug": "Completion time and error count (esoadur2, esoaerr2) are both exactly 0 -- known WebNeuro bug where a genuine timeout gets silently recorded as instant, error-free completion instead of being labeled 'TO'.",
    "SoA_completed_no_err_response": "Completion time (esoadur2) is present, meaning the sequence was finished, but the error count (esoaerr2) is missing -- impossible, since finishing requires pressing keys.",
    "SoA_completed_no_conn_time": "Completion time (esoadur2) is present, meaning the sequence was finished, but the average connection time (scavr0t2) is missing -- impossible for the same reason.",
    "SoA_err_conn_missing_mismatch": "Error count (esoaerr2) and average connection time (scavr0t2) should go missing together (both trigger on 'no response'), but only one of them is missing here.",
}

# which raw variable(s) each check is actually about -- used to label
# issues with the specific column(s) at fault, not just the check name
CHECK_VARIABLES = {
    "maze_errk_not_gt_overk": ["emzerrk", "emzoverk"],
    "maze_trlsk_below_floor": ["emztrlsk"],
    "maze_trlsk_implausibly_high": ["emztrlsk"],
    "maze_compk_eq_0": ["emzcompk"],
    "maze_compk_not_gt_initk": ["emzcompk", "emzinitk"],
    "maze_compk_over_timeout": ["emzcompk"],
    "maze_initk_over_timeout": ["emzinitk"],
    "maze_partial_missing": MAZE_COLS,
    "maze_errk_zero_impossible": ["emzerrk"],
    "maze_overk_zero_review": ["emzoverk"],
    "maze_initk_zero_impossible": ["emzinitk"],
    "maze_trlsk_eq_2_impossible": ["emztrlsk"],
    "maze_negative_value": MAZE_COLS,
    "maze_non_integer_value": ["emzerrk", "emzoverk", "emztrlsk"],
    "gng_fpk_out_of_range": ["g2fpk"],
    "gng_fnk_out_of_range": ["g2fnk"],
    "gng_errk_out_of_range": ["g2errk"],
    "gng_errk_consistency": ["g2errk", "g2fnk", "g2fpk"],
    "gng_avrtk_impossible": ["g2avrtk", "g2fnk"],
    "gng_never_pressed_bug": ["g2fnk", "g2fpk"],
    "stroop_vcrtne_out_of_range": ["vcrtne"],
    "stroop_vcrtne2_out_of_range": ["vcrtne2"],
    "stroop_rt1_present_score1_zero": ["vcrtne", "vi_sco1"],
    "stroop_rt2_present_score2_zero": ["vcrtne2", "vi_sco2"],
    "stroop_sco1_should_be_missing_bug": ["vcrtne", "vi_sco1"],
    "stroop_sco2_should_be_missing_bug": ["vcrtne2", "vi_sco2"],
    "ds_invalid_value_1_or_2": ["digitsp"],
    "ds_missing_mismatch": ["digitot", "digitsp"],
    "ds_zero_logic_contradiction": ["digitot", "digitsp"],
    "SoA_dur2_over_timeout": ["esoadur2"],
    "SoA_dur2_eq_0": ["esoadur2"],
    "SoA_dur2_below_5000": ["esoadur2"],
    "SoA_err2_gt_25": ["esoaerr2"],
    "SoA_err2_negative": ["esoaerr2"],
    "SoA_err2_non_integer": ["esoaerr2"],
    "SoA_conn2_eq_0": ["scavr0t2"],
    "SoA_dur2_err2_zero_timeout_bug": ["esoadur2", "esoaerr2"],
    "SoA_completed_no_err_response": ["esoadur2", "esoaerr2"],
    "SoA_completed_no_conn_time": ["esoadur2", "scavr0t2"],
    "SoA_err_conn_missing_mismatch": ["esoaerr2", "scavr0t2"],
}
